### ISSUE TITLE
[REJECTED] Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [jasonmoo/cryp#1]
Dear Jason,
Could you be so kind to generate ```.exe``` for the rest of us who are mere Windows users w/o compiler?

**Comment by jasonmoo** [comment]
I recommend you install go and build it yourself.

**Comment by sergeevabc** [comment]
Oh, Jason, had user been able to compile in the first place, he would be called a developer.
Front page says “simple tools for encryption”, yet simplicity implies readiness [out of the box][1].

[1]: https://en.wikipedia.org/wiki/Out-of-box_experience
